# Generated by Django 4.1.7 on 2023-05-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_booking', models.DateTimeField(auto_now_add=True)),
                ('id_cruise', models.IntegerField()),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_uslug', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Booking', models.BooleanField()),
            ],
            options={
                'db_table': 'Cruise',
            },
        ),
        migrations.CreateModel(
            name='Gorod',
            fields=[
                ('name', models.CharField(max_length=100000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Gorod',
            },
        ),
        migrations.CreateModel(
            name='Uslug',
            fields=[
                ('name', models.CharField(max_length=100000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Uslug',
            },
        ),
    ]
